services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx_brotli:latest
    container_name: unity-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:rw
